version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/web_dhister
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: application_start.sh
      timeout: 100
      runas: root
    - location: application_stop.sh
      timeout: 100
      runas: root
  
 
